import asyncio
import logging
from datetime import datetime, timedelta

try:
    import websockets
except ModuleNotFoundError:
    print("This example relies on the 'websockets' package.")
    print("Please install it by running: ")
    print()
    print(" $ pip install websockets")
    import sys

    sys.exit(1)

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16 import call, call_result
from ocpp.v16.enums import Action, RegistrationStatus, ClearCacheStatus
from ocpp.v16 import datatypes

logging.basicConfig(level=logging.INFO)

# Define IdTagInfoStatus manually
class IdTagInfoStatus:
    accepted = "Accepted"
    blocked = "Blocked"
    expired = "Expired"
    invalid = "Invalid"
    concurrent_tx = "ConcurrentTx"


class ChargePoint(cp):
    @on(Action.BootNotification)
    async def on_boot_notification(
        self, charge_point_vendor: str, charge_point_model: str, **kwargs
    ):
    
        # await boot_notification_call(self, charge_point_model, charge_point_vendor)
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status=RegistrationStatus.accepted,
        )

    @on(Action.Heartbeat)
    def on_heartbeat(self):
        print("Got a Heartbeat!")
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )
        
    @on(Action.StatusNotification)
    async def on_status_notification(
        self, connector_id: int, error_code: str, status: str, **kwargs
    ):
        logging.info(f"StatusNotification received: Connector ID: {connector_id}, "
                     f"Status: {status}, Error Code: {error_code}")
        # You can process the status here (e.g., log it, update a database, etc.)
        return call_result.StatusNotificationPayload()

    @on(Action.StartTransaction)
    async def on_start_transaction(
        self, connector_id: int, id_tag: str, timestamp: str, meter_start: int, **kwargs
    ):
        logging.info(f"StartTransaction received: Connector ID: {connector_id}, "
                     f"ID Tag: {id_tag}, Timestamp: {timestamp}, Meter Start: {meter_start}")
        
        # Normally, you'd perform validation here, such as checking the id_tag in your database.
        # For now, let's assume the transaction is always authorized.
        
        # Send a StartTransactionResponse with a transaction ID and status.
        return call_result.StartTransactionPayload(
            transaction_id=1,  # This should be a unique ID, typically generated by your system
            id_tag_info={
                "status": IdTagInfoStatus.accepted,
                "expiryDate": (datetime.utcnow() + timedelta(days=365)).isoformat() + "Z",
            }
        )

    @on(Action.MeterValues)
    async def on_meter_values(
        self, connector_id: int, transaction_id: int, meter_value: list, **kwargs
    ):
        logging.info(f"MeterValues received: Connector ID: {connector_id}, "
                     f"Transaction ID: {transaction_id}, Meter Values: {meter_value}")
        
        # Here, you would typically process and store the meter values, e.g., update a database.
        
        # Respond with an empty payload as per the OCPP 1.6 specification.
        return call_result.MeterValuesPayload()

    @on(Action.StopTransaction)
    async def on_stop_transaction(
        self, transaction_id: int, meter_stop: int, timestamp: str, id_tag: str = None, **kwargs
    ):
        """
        Handle StopTransaction requests sent by the charge point.

        Parameters:
        - transaction_id (int): The ID of the transaction being stopped.
        - meter_stop (int): The meter reading at the end of the transaction (in Wh or kWh).
        - timestamp (str): The timestamp when the transaction was stopped.
        - id_tag (str, optional): The ID tag used to stop the transaction, if available.
        """
        logging.info(f"StopTransaction received: Transaction ID: {transaction_id}, "
                     f"Meter Stop: {meter_stop}, Timestamp: {timestamp}, ID Tag: {id_tag}")
        
        # You might want to log the transaction details to a database or perform other actions here.
        # Example: Update transaction status in the database, calculate the total energy consumed, etc.
        
        # Send a StopTransactionResponse
        return call_result.StopTransactionPayload(
            id_tag_info={
                "status": "Accepted",
            }
        )
        


        
async def on_connect(websocket, path):
    """For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """

    logging.info(f"Received connection from {path}")
    logging.info(f"Request headers: {websocket.request_headers}")
    try:
        requested_protocols = websocket.request_headers["Sec-WebSocket-Protocol"]
    except KeyError:
        logging.error("Client hasn't requested any Subprotocol. Closing Connection")
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning(
            "Protocols Mismatched | Expected Subprotocols: %s,"
            " but client supports  %s | Closing connection",
            websocket.available_subprotocols,
            requested_protocols,
        )
        return await websocket.close()

    charge_point_id = path.strip("/")
    print(charge_point_id)
    cp = ChargePoint(charge_point_id, websocket)

    await cp.start()
    # await clear_cache(cp)

async def main():
    server = await websockets.serve(
        on_connect, "0.0.0.0", 8080, subprotocols=["ocpp1.6"]
    )

    logging.info("Server Started listening to new connections...")
    await server.wait_closed()


if __name__ == "__main__":
    # asyncio.run() is used when running this example with Python >= 3.7v
    asyncio.run(main())