import asyncio
import logging
from datetime import datetime, timedelta

try:
    import websockets
except ModuleNotFoundError:
    print("This example relies on the 'websockets' package.")
    print("Please install it by running: ")
    print()
    print(" $ pip install websockets")
    import sys

    sys.exit(1)

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16 import call, call_result
from ocpp.v16.enums import Action, RegistrationStatus, ClearCacheStatus
from ocpp.v16 import datatypes

logging.basicConfig(level=logging.INFO)

config_status = {}
charge_points = {}

# Define IdTagInfoStatus manually
class IdTagInfoStatus:
    accepted = "Accepted"
    blocked = "Blocked"
    expired = "Expired"
    invalid = "Invalid"
    concurrent_tx = "ConcurrentTx"


class ChargePoint(cp):
    @on(Action.BootNotification)
    async def on_boot_notification(
        self, charge_point_vendor: str, charge_point_model: str, **kwargs
    ):
    
        # await boot_notification_call(self, charge_point_model, charge_point_vendor)
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status=RegistrationStatus.accepted,
        )

    @on(Action.Heartbeat)
    def on_heartbeat(self):
        print("Got a Heartbeat!")
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )
        
    @on(Action.StatusNotification)
    async def on_status_notification(
        self, connector_id: int, error_code: str, status: str, **kwargs
    ):
        logging.info(f"StatusNotification received: Connector ID: {connector_id}, "
                     f"Status: {status}, Error Code: {error_code}")
        # You can process the status here (e.g., log it, update a database, etc.)
        return call_result.StatusNotificationPayload()

    @on(Action.StartTransaction)
    async def on_start_transaction(
        self, connector_id: int, id_tag: str, timestamp: str, meter_start: int, **kwargs
    ):
        logging.info(f"StartTransaction received: Connector ID: {connector_id}, "
                     f"ID Tag: {id_tag}, Timestamp: {timestamp}, Meter Start: {meter_start}")
        
        # Normally, you'd perform validation here, such as checking the id_tag in your database.
        # For now, let's assume the transaction is always authorized.
        
        # Send a StartTransactionResponse with a transaction ID and status.
        return call_result.StartTransactionPayload(
            transaction_id=1,  # This should be a unique ID, typically generated by your system
            id_tag_info={
                "status": IdTagInfoStatus.accepted,
                "expiryDate": (datetime.utcnow() + timedelta(days=365)).isoformat() + "Z",
            }
        )

    @on(Action.MeterValues)
    async def on_meter_values(
        self, connector_id: int, transaction_id: int, meter_value: list, **kwargs
    ):
        logging.info(f"MeterValues received: Connector ID: {connector_id}, "
                     f"Transaction ID: {transaction_id}, Meter Values: {meter_value}")
        
        # Here, you would typically process and store the meter values, e.g., update a database.
        
        # Respond with an empty payload as per the OCPP 1.6 specification.
        return call_result.MeterValuesPayload()

async def send_remote_stop_transaction(cp, transaction_id):
    request = call.RemoteStopTransactionPayload(transaction_id=transaction_id)

    try:
        # Send the SetChargingProfile request and wait for the response
        timeout_seconds = 180
        response = await asyncio.wait_for(cp.call(request), timeout=timeout_seconds)

        if response.status == "Accepted":
            print(f"Transaction {transaction_id} successfully stopped.")
        else:
            print(f"Failed to stop transaction {transaction_id}: {response.status}")

    except asyncio.TimeoutError:
        logging.error(f"Timed out waiting for the RemoteStartTransaction response after {timeout_seconds} seconds.")
    
    except Exception as e:
        logging.error(f"Error sending RemoteStartTransaction: {e}")

async def on_connect(websocket, path):
    charge_point_id = path.strip("/")
    cp = ChargePoint(charge_point_id, websocket)

    # Add the connected charge point to the dictionary
    charge_points[charge_point_id] = cp

    # Start the charge point logic in its own task
    start_task = asyncio.create_task(cp.start())

    if not config_status.get(charge_point_id, False):
        # Wait for the specific charger to connect before sending profile
        if charge_point_id == 'UKAGKHTV':
            print(charge_points)
            # Stop the transaction with ID 1
            transaction_id = 1
            await send_remote_stop_transaction(charge_points['UKAGKHTV'], transaction_id)
            config_status[charge_point_id] = True

    # Wait for the start task to complete, which keeps the connection open
    try:
        await start_task
    except asyncio.CancelledError:
        logging.info(f"Connection closed for charge point: {charge_point_id}")



async def main():
    server = await websockets.serve(on_connect, "0.0.0.0", 8080, subprotocols=["ocpp1.6"])
    logging.info("Server Started listening to new connections...")
    await server.wait_closed()

if __name__ == "__main__":
    asyncio.run(main())
